### ISSUE TITLE
Help us

### ISSUE THREAD

**Issue by kurniawan77** [ewjmulder/hue-bridge-simulator#2]
Hi,

Not an issue here really but we are trying to get connected to the Toon with an other Hue simulator over here.. [https://github.com/mariusmotea/diyHue/issues/23](https://github.com/mariusmotea/diyHue/issues/23)
It connects to all Hue apps and even with Domoticz but no way with the Toon. It will be great if you would like to dive in and share your knowledge with us.

Regards

**Comment by ewjmulder** [comment]
Hi there,

I'll try to help you with this. BTW, funny to see you guys quoting my personal 'braindump' in IDEAS.txt :-D
I think that contains the key to the solution: Toon actually seems not to use the M-SEARCH for discovering the Hue bridge, it only uses the 6 'broadcast' messages that the bridge does automatically every minute. As stated in the documentation, I just had to exactly replicate these messages for Toon to find my simulated bridge. I only changed the location of the description.xml, the mac address and the bridge name, as you can see in my code.

Did you try to auto-broadcast those 6 messages every minute on the network? I don't think you can get it working with just M-SEARCH responses, since that is not the way Toon discovers a Hue bridge.

Let me know if it works or if you need any more help.

Good luck, Erik

**Comment by kurniawan77** [comment]
Hi,

Thanks for your response. Mariusmotea's script now broadcasts the 6 messages within 1 minute but we are not sure about the delay between the two same messages and the two different messages. Also, must it be in the same order? It seems that the Toon is very picky as i can't get a connection. I have waited a few minutes, rebooted, wait again. Even tried the search button on Toon (don't see any sign of search with wireshark, just like you mentioned in "ideas") but no go... 

And also, we get the mac address from the pi and use this in the broadcast message and description.xml or must we use a 00:17:88:xx:xx:xx Phillips Hue mac address ?

Could you give us some advise?

**Comment by ewjmulder** [comment]
Sorry, I must have missed the notification of your reply. In case you still need to figure this out: here is some more advice.

You can listen in (with Wireshark) on an actual Hue bridge or my simulator to see the message content and timing. That's what I did to get a successful connection to Toon. I can't give you any more advice on the messages. Another important thing is to make sure the UPnP messages can actually travel from your running script to Toon. So make sure any network devices in between, like a router / repeater / access point / etc allow UPnP traffic.

The search button on Toon is actually not doing anything else then listen for messages for 1 minute and reports any bridges that it found in that time. Good luck with getting the Toon to work!

**Comment by kurniawan77** [comment]
That is actually what i did. I bought a real Hue bridge and "wiresharked" it. The real hue bridge was also able to connect to the Toon, so i don't think there is anything wrong with my router setup.  Mariusmotea replicated the messages that i received but it's still a no go. I understand you can't help us more, i have tried other emulator's like HA-bridge and the hue emulator in home-assistant... no go. It's seems that the Toon looks at `https://www.meethue.com/api/nupnp` to get connected to the hue.
